name: release and publish
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: matches(github.event.head_commit.message, '.*[0-9]+\.[0-9]+\.[0-9]+.*')
    steps:
      - uses: actions/checkout@v2
      - name: Extract Version Name
        run: |
          VERSION=$(echo "${{ github.event.head_commit.message }}" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | tr -d '\n')
          echo "VERSION=v$VERSION" >> "$GITHUB_ENV"
        id: extract_version_name
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}

  publish-npm:
    needs: release
    runs-on: ubuntu-latest
    if: needs.release.result == 'success'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org/'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
